[package]
name = "kore-base"
version.workspace = true
edition.workspace = true

[dependencies]
actor = { path = "../../rush-rs/actor" }
argon2 = "0.5"
async-trait = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
generic-array = {version = "1.0", features = ["zeroize"] }
identity = { path = "../identity"}
json-patch = { version = "2.0" }
jsonschema = { version = "0.18", default_features = false }
memsecurity = { version = "3.5", features = ["encryption"]}
rocksdb_db = { path = "../../rush-rs/databases/rocksdb_db", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlite_db = { path = "../../rush-rs/databases/sqlite_db", optional = true }
store = { path = "../../rush-rs/store" }
thiserror = { workspace = true }
time = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tracing-test = { workspace = true }

[features]
default = ["rocksdb"]
rocksdb = ["rocksdb_db"]
sqlite = ["sqlite_db"]
